### ISSUE TITLE
 Error: Type 'TextEditingActionTarget' not found。执行flutter clean后重新下载依然报错

### ISSUE THREAD

**Issue by dasewan** [chn-sunch/flutter_mycommunity_app#3]
![image](https://user-images.githubusercontent.com/8346782/160082235-60edcd63-5695-4835-b66c-238dbbf7c205.png)

Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Launching lib\main.dart on MI 8 in debug mode...
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
/E:/program/flutter_windows_2.0.3-stable/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text-8.0.2/lib/src/selection/extended_text_selection.dart:136:10: Error: Type 'TextEditingActionTarget' not found.
    with TextEditingActionTarget
         ^^^^^^^^^^^^^^^^^^^^^^^
/E:/program/flutter_windows_2.0.3-stable/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text_field-9.0.3/lib/src/extended_editable_text.dart:1179:9: Error: Type 'TextEditingActionTarget' not found.

        TextEditingActionTarget,
        ^^^^^^^^^^^^^^^^^^^^^^^
/E:/program/flutter_windows_2.0.3-stable/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text-8.0.2/lib/src/selection/extended_text_selection.dart:135:7: Error: The type 'TextEditingActionTarget' can't be mixed in.
class ExtendedTextSelectionState extends State<ExtendedTextSelection>
      ^
/E:/program/flutter_windows_2.0.3-stable/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text_field-9.0.3/lib/src/extended_editable_text.dart:1174:7: Error: The type 'TextEditingActionTarget' can't be mixed in.
class ExtendedEditableTextState extends State<ExtendedEditableText>

      ^
/E:/program/flutter_windows_2.0.3-stable/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text_field-9.0.3/lib/src/extended_editable_text.dart:2598:11: Error: Superclass has no method named 'copySelection'.
    super.copySelection(cause);
          ^^^^^^^^^^^^^
/E:/program/flutter_windows_2.0.3-stable/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text_field-9.0.3/lib/src/extended_editable_text.dart:2628:11: Error: Superclass has no method named 'cutSelection'.

    super.cutSelection(cause);
          ^^^^^^^^^^^^
/E:/program/flutter_windows_2.0.3-stable/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text_field-9.0.3/lib/src/extended_editable_text.dart:2638:11: Error: Superclass has no method named 'pasteText'.
    super.pasteText(cause);
          ^^^^^^^^^

/E:/program/flutter_windows_2.0.3-stable/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text_field-9.0.3/lib/src/extended_editable_text.dart:2648:11: Error: Superclass has no method named 'selectAll'.
    super.selectAll(cause);
          ^^^^^^^^^

/E:/program/flutter_windows_2.0.3-stable/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text_field-9.0.3/lib/src/extended_editable_text.dart:2693:11: Error: Superclass has no method named 'setSelection'.
    super.setSelection(nextSelection, cause);
          ^^^^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'E:\program\flutter_windows_2.0.3-stable\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1105

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'E:\program\flutter_windows_2.0.3-stable\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
BUILD FAILED in 1m 14s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by chn-sunch** [comment]
这是extended_text_field 组件 build 出错 可能你的版本2.10.3  extended_text_field 不兼容导致的

**Comment by chn-sunch** [comment]
@dasewan 把 extended_text_field 更新到最新版本试试 https://pub.flutter-io.cn/packages/extended_text_field/changelog
